apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: openshift-config
stringData:
  htpasswd: |
{{- range .Values.users }}
    {{ .name }}:{{ printf "%s" (b64enc (printf "%s" .password)) | printf "%s" }}
{{- end }}