apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: customization-appset
  namespace: openshift-gitops  # Check if this is the correct namespace
spec:
  generators:
    - list:
        elements:
          - branch: main
            namespace: openshift-config
            path: openshift-customization
            project: default
            team: openshift-customization
            url: https://github.com/Hashlama-016/Argo-Configs.git
  template:
    metadata:
      name: "{{team}}"
      namespace: "{{namespace}}"
    spec:
      project: "{{project}}"
      source:
        repoURL: "{{url}}"
        targetRevision: "{{branch}}"
        path: "{{path}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
