apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hashlama-016/Argo-Configs.git
    targetRevision: main
    path: apps
  destination:
    server: https://api.hashlama016-black-openshift.bsmch.net:6443
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true