apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: teams-appset
  namespace: openshift-gitops 
spec:
  generators:
    - list: 
        elements:
          - team: airflow
            namespace: airflow
            url: https://github.com/Hashlama-016/Exodus-team.git
            branch: airflow
            path: airflow
            project: airflow
          - team: portal
            namespace: portal
            url: http://10.50.1.4/Hashlama_2/developer-portal.git
            branch: main
            path: helm-app
            project: portal 
  template:
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: "{{team}}"
      namespace: openshift-gitops  
    spec:
      project: "{{project}}"
      source:
        repoURL: "{{url}}"
        targetRevision: "{{branch}}"
        path: "{{path}}"
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
