{{- range .Values.teams }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-svc
  namespace: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  ports:
    - port: {{ .port }} 
      targetPort: {{ .port }}
      protocol: TCP
  selector:
    app: {{ .name }}  
{{- end }}