{{- range .Values.teams }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-svc
  namespace: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  ports:
    - port:  8080 
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .name }}  
{{- end }}