{{- range .Values.teams }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "{{ . }}"
  namespace: openshift-gitops
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: "{{ . }}"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: "{{ . }}-team"
      policies:
        - p, proj:{{ . }}:{{ . }}-team, applications, get, {{ . }}/*, allow
        - p, proj:{{ . }}:{{ . }}-team, applications, sync, {{ . }}/*, allow
      groups:
        - "{{ . }}-team"
---
{{- end }}
