apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: openshift-gitops
data:
  policy.csv: |-
    g, system:cluster-admins, role:admin
    g, cluster-admins, role:admin
{{- range .Values.teams }}
    g, {{ . }}, proj:default, role:admin
{{- end }}
  policy.default: ''
  scopes: '[groups]'