{{- range .Values.teams }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ . }}
  namespace: {{ . }}
spec:
  # No hard limits specified
  # But we can still define limits per team
  {{- if or (eq . "airflow") (eq . "portal") (eq . "image-builder") }}
  limits.cpu: "1.5"
  limits.memory: "8Gi"
  pods: "100"
  {{- else }}
  limits.cpu: "0.5"
  limits.memory: "3Gi"
  pods: "50"
  {{- end }}
{{- end }}