{{- range .Values.teams }}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ . }}
  namespace: {{ . }}
spec:
  hard:
    {{- if or (eq . "airflow") (eq . "portal") (eq . "image-builder") }}
    limits.cpu: "8"
    limits.memory: "16Gi"
    pods: "100"
    {{- else }}
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "50"
    {{- end }}
{{- end }}
