{{- range .Values.teams }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ . }}
  namespace: {{ . }}
spec:
  hard:
    limits.cpu: "1"
    limits.memory: "3.55Gi"
    pods: "50"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: {{ . }}
spec:
  limits:
    - type: Container
      default:
        cpu: 1m
        memory: 3.5Gi
---
{{- end }}