apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: in-cluster
    targetRevision: main
    path: services/rabbitmq
  destination:
    server: https://api.hashlama016-black-openshift.bsmch.net:6443
    namespace: rabbitmq-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true