apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://github.com/your-org/argo-configs.git
    targetRevision: main
    path: services/rabbitmq
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true