apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Hashlama-016/Argo-Configs.git
    targetRevision: main
    path: services/rabbitmq
  destination:
    server: in-cluster
    namespace: rabbitmq-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true