apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: htpasswd-secret-application
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: manifests
    repoURL: 'https://github.com/Hashlama-016/Argo-Configs'
    targetRevision: main
    chart: users
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
