apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: users-auth
  namespace: openshift-gitops
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: users
    repoURL: 'https://github.com/Hashlama-016/Argo-Configs'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
